Update Rails application based on suspenders
Update some suspenders-generated files to match our latest
recommendations.

Also update the ruby version.

diff --git a/example_apps/rails/bin/setup b/example_apps/rails/bin/setup
--- a/example_apps/rails/bin/setup
+++ b/example_apps/rails/bin/setup
@@ -3,24 +3,9 @@
 # Set up Rails app. Run this script immediately after cloning the codebase.
 # https://github.com/thoughtbot/guides/tree/master/protocol
 
+# Exit if any subcommand fails
+set -e
+
 # Set up Ruby dependencies via Bundler
-bundle install
-
-# Set up the database
-bundle exec rake db:setup
-
-# Set up configurable environment variables
-if [ ! -f .env ]; then
-  cp .sample.env .env
-fi
-
-# Pick a port for Foreman
-echo "port: 7000" > .foreman
-
-# Set up DNS via Pow
-if [ -d ~/.pow ]
-then
-  echo 7000 > ~/.pow/`basename $PWD`
-else
-  echo "Pow not set up but the team uses it for this project. Setup: http://goo.gl/RaDPO"
-fi
+gem install bundler --conservative
+bundle check || bundle install
